### ISSUE TITLE
Cobh Belvast time offset 30sec

### ISSUE THREAD

**Issue by halohalor** [Warsen/Mabinogi-TT#1]
Hi
I follow ur guide to offset 11min after fine tune with other ship timing. no matter how i try cobh belvast always off by 30sec.
please update this part

**Comment by halohalor** [comment]
the belvast to cobh timer on ship shhould be 2min, not 2min 30sec.

**Comment by Warsen** [comment]
You are right. I checked it recently and it's indeed off by 30 seconds, even though I could swear it was correct a year ago. I'll fix it and update it this week for sure.

**Comment by Warsen** [comment]
Fixed in a3d3126. Released v1.1
